'use client'

import Script from 'next/script'
import './globals.css'
import { Inter } from 'next/font/google'
import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: "/manifest.json",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <head>
        {/* <Script src='https://www.gstatic.com/firebasejs/10.0.0/firebase-messaging-compat.js' />
        <Script src='https://www.gstatic.com/firebasejs/10.0.0/firebase-app-compat.js' /> */}
      </head>
      <body className={inter.className}>
        <CacheProvider>
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  )
}
